/*******************************************************************************/
/*  This file is auto-generated by GUIX Studio. Do not edit this file by hand. */
/*  Modifications to this file should only be made by running the GUIX Studio  */
/*  application and re-generating the application. For more information please */
/*  refer to the GUIX Studio user's guide, or visit our web site at            */
/*  www.expresslogic.com.                                                      */
/*                                                                             */
/*  GUIX Studio Revision 5.4.1.1                                               */
/*  Date (dd.mm.yyyy): 11. 2.2019   Time (hh:mm): 01:15                        */
/*******************************************************************************/


#define GUIX_STUDIO_GENERATED_FILE
#include <stddef.h>
#include "guiapp_resources.h"
#include "guiapp_specifications.h"

MAIN_SCREEN_CONTROL_BLOCK main_screen;
SYSTEM_DIAGNOSTICS_CONTROL_BLOCK system_diagnostics;
static GX_WIDGET *gx_studio_nested_widget_create(GX_BYTE *control, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent);


GX_DISPLAY display_1_control_block;
GX_CANVAS  display_1_canvas_control_block;
GX_WINDOW_ROOT display_1_root_window;
static VOID gx_studio_screen_toggle(GX_WIDGET *target1, GX_WIDGET *target2)
{
    GX_WIDGET *parent = target1->gx_widget_parent;
    if (parent)
    {
        gx_widget_detach(target1);
        gx_widget_attach(parent, target2);
        if (target1->gx_widget_status & GX_STATUS_STUDIO_CREATED)
        {
            gx_widget_delete(target1);
        }
    }
}

static GX_WIDGET *gx_studio_action_target_get(GX_CONST GX_STUDIO_ACTION *action)
{
    GX_WIDGET *target = GX_NULL;
    GX_STUDIO_WIDGET *widget_define;

    if (action->flags & GX_ACTION_FLAG_DYNAMIC_TARGET)
    {
                                             /* dynamically create the target widget */
        widget_define = (GX_STUDIO_WIDGET *) action->target;
        gx_widget_find(action->parent, widget_define->widget_id, 1, &target);
        if (target == GX_NULL)
        {
            target = gx_studio_widget_create(GX_NULL, widget_define, GX_NULL);
        }
        if (target)
        {
            target->gx_widget_status |= GX_STATUS_STUDIO_CREATED;
        }
    }
    else
    {
        target = (GX_WIDGET *) action->target;
    }
    return target;
}

static GX_WIDGET *gx_studio_action_target_find(GX_CONST GX_STUDIO_ACTION *action)
{
    GX_WIDGET *target = GX_NULL;
    GX_STUDIO_WIDGET *widget_define;

    if (action->flags & GX_ACTION_FLAG_DYNAMIC_TARGET)
    {
                                             /* Find the dynamically created target */
        widget_define = (GX_STUDIO_WIDGET *) action->target;
        gx_widget_find(action->parent, widget_define->widget_id, GX_SEARCH_DEPTH_INFINITE, &target);
    }
    else
    {
        target = (GX_WIDGET *) action->target;
    }
    return target;
}

static VOID gx_studio_animation_execute(GX_CONST GX_STUDIO_ACTION *action)
{
    GX_ANIMATION *animation;
    GX_ANIMATION_INFO animation_info;
    GX_WIDGET *target;

    gx_system_animation_get(&animation);
    if (animation)
    {
        animation_info = *action->animation;
        if (action->flags & GX_ACTION_FLAG_DYNAMIC_TARGET)
        {
            target = gx_studio_action_target_get(action);
            animation_info.gx_animation_target = target;
        }
        if (animation_info.gx_animation_target)
        {
            gx_animation_start(animation, &animation_info);
        }
    }
}

static UINT gx_studio_auto_event_handler(GX_WIDGET *widget, GX_EVENT *event_ptr, GX_CONST GX_STUDIO_EVENT_PROCESS *record)
{
    UINT status = GX_SUCCESS;
    GX_CONST GX_STUDIO_ACTION *action;
    GX_CONST GX_WIDGET *parent;
    GX_WIDGET *target;
    GX_CONST GX_STUDIO_EVENT_ENTRY *entry = record->event_table;

    while(entry->event_type)
    {
        if (entry->event_type == event_ptr->gx_event_type)
        {
            action = entry->action_list;

            while(action->opcode)
            {
                switch(action->opcode)
                {
                case GX_ACTION_TYPE_ATTACH:
                    parent = action->parent;
                    target = gx_studio_action_target_get(action);
                    if (parent && target)
                    {
                        gx_widget_attach(parent, target);
                    }
                    break;

                case GX_ACTION_TYPE_DETACH:
                    target = gx_studio_action_target_find(action);
                    if (target)
                    {
                        gx_widget_detach(target);
                        if (target->gx_widget_status & GX_STATUS_STUDIO_CREATED)
                        {
                            gx_widget_delete(target);
                        }
                    }
                    break;

                case GX_ACTION_TYPE_TOGGLE:
                    target = gx_studio_action_target_get(action);
                    gx_studio_screen_toggle(widget, target);
                    break;

                case GX_ACTION_TYPE_SHOW:
                    gx_widget_show((GX_WIDGET *) action->target);
                    break;

                case GX_ACTION_TYPE_HIDE:
                    gx_widget_hide((GX_WIDGET *) action->target);
                    break;

                case GX_ACTION_TYPE_ANIMATION:
                    gx_studio_animation_execute(action);
                    break;

                case GX_ACTION_TYPE_WINDOW_EXECUTE:
                    parent = widget->gx_widget_parent;
                    target = gx_studio_action_target_get(action);
                    if (parent && target)
                    {
                        gx_widget_attach(parent, target);
                        gx_window_execute((GX_WINDOW *) target, GX_NULL);
                    }
                    break;

                case GX_ACTION_TYPE_WINDOW_EXECUTE_STOP:
                    return event_ptr->gx_event_sender;

                default:
                    break;
                }
                action++;
            }
        }
        entry++;
    }

    if (record->chain_event_handler)
    {
        status = record->chain_event_handler(widget, event_ptr);
    }
    return status;
}


UINT gx_studio_text_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_TEXT_BUTTON *button = (GX_TEXT_BUTTON *) control_block;
    GX_TEXT_BUTTON_PROPERTIES *props = (GX_TEXT_BUTTON_PROPERTIES *) info->properties;
    status = gx_text_button_create(button, info->widget_name, parent, props->string_id, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        gx_text_button_font_set(button, props->font_id);
        gx_text_button_text_color_set(button, props->normal_text_color_id, props->selected_text_color_id);
    }
    return status;
}

UINT gx_studio_prompt_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_PROMPT *prompt = (GX_PROMPT *) control_block;
    GX_PROMPT_PROPERTIES *props = (GX_PROMPT_PROPERTIES *) info->properties;
    status = gx_prompt_create(prompt, info->widget_name, parent, props->string_id, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        gx_prompt_font_set(prompt, props->font_id);
        gx_prompt_text_color_set(prompt, props->normal_text_color_id, props->selected_text_color_id);
    }
    return status;
}

UINT gx_studio_window_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_WINDOW *window = (GX_WINDOW *) control_block;
    GX_WINDOW_PROPERTIES *props = (GX_WINDOW_PROPERTIES *) info->properties;
    status = gx_window_create(window, info->widget_name, parent, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        if (props->wallpaper_id)
        {
            gx_window_wallpaper_set(window, props->wallpaper_id, info->style & GX_STYLE_TILE_WALLPAPER);
        }
    }
    return status;
}
static GX_STUDIO_EVENT_ENTRY gx_studio_main_screen_event_table[] = {
    {0, GX_NULL}
};

GX_STUDIO_EVENT_PROCESS main_screen_event_chain = {gx_studio_main_screen_event_table, (UINT (*)(GX_WIDGET *, GX_EVENT *))main_screen_handler};
static UINT gx_studio_main_screen_event_process(GX_WIDGET *target, GX_EVENT *event_ptr)
{
    return (gx_studio_auto_event_handler(target, event_ptr, &main_screen_event_chain));
}

GX_WINDOW_PROPERTIES main_screen_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_PROMPT_PROPERTIES main_screen_embedded_sw_properties =
{
    GX_STRING_ID_EMBEDDED_SW,                /* string id                      */
    GX_FONT_ID_EMBEDDED_SW,                  /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES main_screen_MotorSpeed_properties =
{
    GX_STRING_ID_SPEED_PLACEHOLDER,          /* string id                      */
    GX_FONT_ID_SPEED_TEXT,                   /* font id                        */
    GX_COLOR_ID_SELECTED_FILL,               /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES main_screen_SpeedCmd_properties =
{
    GX_STRING_ID_SPEED_CMD_PLACEHOLDER,      /* string id                      */
    GX_FONT_ID_DUTY_CYCLE,                   /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_SLIDER_TICK                  /* selected text color            */
};
GX_WINDOW_PROPERTIES main_screen_animation_window_properties =
{
    GX_PIXELMAP_ID_SPEED_CYCLE               /* wallpaper pixelmap id          */
};
GX_PROMPT_PROPERTIES main_screen_rpm_properties =
{
    GX_STRING_ID_RPM,                        /* string id                      */
    GX_FONT_ID_SPEED_TEXT,                   /* font id                        */
    GX_COLOR_ID_SELECTED_FILL,               /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES main_screen_hw_version_properties =
{
    GX_STRING_ID_HW_VERSION,                 /* string id                      */
    GX_FONT_ID_SW_AND_HW_VERSIONS,           /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_CANVAS                       /* selected text color            */
};
GX_PROMPT_PROPERTIES main_screen_sw_version_properties =
{
    GX_STRING_ID_SW_VERSION,                 /* string id                      */
    GX_FONT_ID_SW_AND_HW_VERSIONS,           /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_CANVAS                       /* selected text color            */
};
GX_PROMPT_PROPERTIES main_screen_ceseq_c001_ceseq_p001_properties =
{
    GX_STRING_ID_CESEQ_C001_CESEQ_P001,      /* string id                      */
    GX_FONT_ID_SW_AND_HW,                    /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_CANVAS                       /* selected text color            */
};
GX_PROMPT_PROPERTIES main_screen_m4_dc_mvc_1909_properties =
{
    GX_STRING_ID_M4_DC_MVC,                  /* string id                      */
    GX_FONT_ID_SW_AND_HW,                    /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_CANVAS                       /* selected text color            */
};
GX_WINDOW_PROPERTIES main_screen_aptiv_signature_properties =
{
    GX_PIXELMAP_ID_APTIV_RESIZED             /* wallpaper pixelmap id          */
};
GX_PROMPT_PROPERTIES main_screen_sw_engineers_properties =
{
    GX_STRING_ID_SOFTWARE_ENGINEERS,         /* string id                      */
    GX_FONT_ID_SW_ENGINEERS,                 /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_CANVAS                       /* selected text color            */
};
GX_PROMPT_PROPERTIES main_screen_gemma_corona_properties =
{
    GX_STRING_ID_GEMMA_CORONA,               /* string id                      */
    GX_FONT_ID_ENGINEERS,                    /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_CANVAS                       /* selected text color            */
};
GX_PROMPT_PROPERTIES main_screen_josue_uribe_properties =
{
    GX_STRING_ID_JOSUE_URIBE,                /* string id                      */
    GX_FONT_ID_ENGINEERS,                    /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_CANVAS                       /* selected text color            */
};
GX_PROMPT_PROPERTIES main_screen_victor_alvarado_properties =
{
    GX_STRING_ID_VICTOR_ALVARADO,            /* string id                      */
    GX_FONT_ID_ENGINEERS,                    /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_CANVAS                       /* selected text color            */
};
GX_PROMPT_PROPERTIES main_screen_duty_cycle_properties =
{
    GX_STRING_ID_DUTY_CYCLE,                 /* string id                      */
    GX_FONT_ID_DUTY_CYCLE,                   /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_CANVAS                       /* selected text color            */
};
GX_PROMPT_PROPERTIES main_screen_unit_percentage_properties =
{
    GX_STRING_ID_PERCENTAGE,                 /* string id                      */
    GX_FONT_ID_DUTY_CYCLE,                   /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_CANVAS                       /* selected text color            */
};
GX_TEXT_BUTTON_PROPERTIES main_screen_windowchanger_sys_properties =
{
    GX_STRING_ID_WINDOW_CHANGER_SYS,         /* string id                      */
    GX_FONT_ID_WINDOW_CHANGER,               /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_SLIDER_TICK                  /* selected text color            */
};

GX_CONST GX_STUDIO_WIDGET main_screen_windowchanger_sys_define =
{
    "windowchanger_sys",
    GX_TYPE_TEXT_BUTTON,                     /* widget type                    */
    ID_WINDOWCHANGER_SYS,                    /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_TEXT_BUTTON),                  /* control block size             */
    GX_COLOR_ID_WINDOW_CHANGER,              /* normal color id                */
    GX_COLOR_ID_SHINE,                       /* selected color id              */
    gx_studio_text_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {149, 130, 228, 154},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_windowchanger_sys), /* control block */
    (void *) &main_screen_windowchanger_sys_properties /* extended properties  */
};

GX_CONST GX_STUDIO_WIDGET main_screen_unit_percentage_define =
{
    "unit_percentage",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {196, 77, 210, 100},                     /* widget size                    */
    &main_screen_windowchanger_sys_define,   /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_unit_percentage), /* control block */
    (void *) &main_screen_unit_percentage_properties /* extended properties    */
};

GX_CONST GX_STUDIO_WIDGET main_screen_duty_cycle_define =
{
    "duty_cycle",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_DUTY_CYCLE,                           /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_CANVAS,                      /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {155, 57, 224, 80},                      /* widget size                    */
    &main_screen_unit_percentage_define,     /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_duty_cycle), /* control block */
    (void *) &main_screen_duty_cycle_properties /* extended properties         */
};

GX_CONST GX_STUDIO_WIDGET main_screen_victor_alvarado_define =
{
    "victor_alvarado",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_VICTOR_ALVARADO,                      /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {12, 295, 126, 314},                     /* widget size                    */
    &main_screen_duty_cycle_define,          /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_victor_alvarado), /* control block */
    (void *) &main_screen_victor_alvarado_properties /* extended properties    */
};

GX_CONST GX_STUDIO_WIDGET main_screen_josue_uribe_define =
{
    "josue_uribe",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_JOSUE_URIBE,                          /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {12, 278, 126, 297},                     /* widget size                    */
    &main_screen_victor_alvarado_define,     /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_josue_uribe), /* control block */
    (void *) &main_screen_josue_uribe_properties /* extended properties        */
};

GX_CONST GX_STUDIO_WIDGET main_screen_gemma_corona_define =
{
    "gemma_corona",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_GEMMA_CORONA,                         /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {12, 261, 126, 280},                     /* widget size                    */
    &main_screen_josue_uribe_define,         /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_gemma_corona), /* control block */
    (void *) &main_screen_gemma_corona_properties /* extended properties       */
};

GX_CONST GX_STUDIO_WIDGET main_screen_sw_engineers_define =
{
    "sw_engineers",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_SW_ENGINEERS,                         /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {4, 237, 148, 260},                      /* widget size                    */
    &main_screen_gemma_corona_define,        /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_sw_engineers), /* control block */
    (void *) &main_screen_sw_engineers_properties /* extended properties       */
};

GX_CONST GX_STUDIO_WIDGET main_screen_aptiv_signature_define =
{
    "aptiv_signature",
    GX_TYPE_WINDOW,                          /* widget type                    */
    ID_APTIV_SIGNATURE,                      /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE,                    /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_WINDOW),                       /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {134, 299, 236, 316},                    /* widget size                    */
    &main_screen_sw_engineers_define,        /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_aptiv_signature), /* control block */
    (void *) &main_screen_aptiv_signature_properties /* extended properties    */
};

GX_CONST GX_STUDIO_WIDGET main_screen_m4_dc_mvc_1909_define =
{
    "m4_dc_mvc_1909",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_M4_DC_MVC_1909,                       /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {97, 181, 211, 200},                     /* widget size                    */
    &main_screen_aptiv_signature_define,     /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_m4_dc_mvc_1909), /* control block */
    (void *) &main_screen_m4_dc_mvc_1909_properties /* extended properties     */
};

GX_CONST GX_STUDIO_WIDGET main_screen_ceseq_c001_ceseq_p001_define =
{
    "ceseq_c001_ceseq_p001",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_CESEQ_C0010_CESEQ_P001,               /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {97, 207, 236, 226},                     /* widget size                    */
    &main_screen_m4_dc_mvc_1909_define,      /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_ceseq_c001_ceseq_p001), /* control block */
    (void *) &main_screen_ceseq_c001_ceseq_p001_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET main_screen_sw_version_define =
{
    "sw_version",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_SW_VERSION,                           /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {3, 179, 97, 202},                       /* widget size                    */
    &main_screen_ceseq_c001_ceseq_p001_define, /* next widget definition       */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_sw_version), /* control block */
    (void *) &main_screen_sw_version_properties /* extended properties         */
};

GX_CONST GX_STUDIO_WIDGET main_screen_hw_version_define =
{
    "hw_version",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_HW_VERSION,                           /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {3, 205, 97, 228},                       /* widget size                    */
    &main_screen_sw_version_define,          /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_hw_version), /* control block */
    (void *) &main_screen_hw_version_properties /* extended properties         */
};

GX_CONST GX_STUDIO_WIDGET main_screen_rpm_define =
{
    "rpm",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_RPM,                                  /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {31, 113, 110, 136},                     /* widget size                    */
    &main_screen_hw_version_define,          /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_rpm), /* control block     */
    (void *) &main_screen_rpm_properties     /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET main_screen_animation_window_define =
{
    "animation_window",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT,   /* style flags                */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_WINDOW),                       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_CANVAS,                      /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {3, 36, 135, 159},                       /* widget size                    */
    &main_screen_rpm_define,                 /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_animation_window), /* control block */
    (void *) &main_screen_animation_window_properties /* extended properties   */
};

GX_CONST GX_STUDIO_WIDGET main_screen_SpeedCmd_define =
{
    "SpeedCmd",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_CMD_TEXT,                             /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {161, 80, 195, 94},                      /* widget size                    */
    &main_screen_animation_window_define,    /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_SpeedCmd), /* control block */
    (void *) &main_screen_SpeedCmd_properties /* extended properties           */
};

GX_CONST GX_STUDIO_WIDGET main_screen_MotorSpeed_define =
{
    "MotorSpeed",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_SPEED_TEXT,                           /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {30, 89, 109, 112},                      /* widget size                    */
    &main_screen_SpeedCmd_define,            /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_MotorSpeed), /* control block */
    (void *) &main_screen_MotorSpeed_properties /* extended properties         */
};

GX_CONST GX_STUDIO_WIDGET main_screen_embedded_sw_define =
{
    "embedded_sw",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_EMBEDDED_SW,                          /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_CANVAS,                      /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {3, 1, 236, 24},                         /* widget size                    */
    &main_screen_MotorSpeed_define,          /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_SCREEN_CONTROL_BLOCK, main_screen_embedded_sw), /* control block */
    (void *) &main_screen_embedded_sw_properties /* extended properties        */
};

GX_CONST GX_STUDIO_WIDGET main_screen_define =
{
    "main_screen",
    GX_TYPE_WINDOW,                          /* widget type                    */
    ID_MAIN_SCREEN,                          /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_DRAW_SELECTED|GX_STYLE_ENABLED,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(MAIN_SCREEN_CONTROL_BLOCK),       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_CANVAS,                      /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) gx_studio_main_screen_event_process, /* event function override */
    {0, 0, 239, 319},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &main_screen_embedded_sw_define,         /* child widget                   */
    0,                                       /* control block                  */
    (void *) &main_screen_properties         /* extended properties            */
};
static GX_STUDIO_EVENT_ENTRY gx_studio_system_diagnostics_event_table[] = {
    {0, GX_NULL}
};

GX_STUDIO_EVENT_PROCESS system_diagnostics_event_chain = {gx_studio_system_diagnostics_event_table, (UINT (*)(GX_WIDGET *, GX_EVENT *))system_diagnostics_handler};
static UINT gx_studio_system_diagnostics_event_process(GX_WIDGET *target, GX_EVENT *event_ptr)
{
    return (gx_studio_auto_event_handler(target, event_ptr, &system_diagnostics_event_chain));
}

GX_WINDOW_PROPERTIES system_diagnostics_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_TEXT_BUTTON_PROPERTIES system_diagnostics_windowchanger_main_properties =
{
    GX_STRING_ID_WINDOW_CHANGER_MAIN,        /* string id                      */
    GX_FONT_ID_WINDOW_CHANGER,               /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_SLIDER_TICK                  /* selected text color            */
};
GX_PROMPT_PROPERTIES system_diagnostics_battery_shortcut_properties =
{
    GX_STRING_ID_BATTERY_SHORTCUT,           /* string id                      */
    GX_FONT_ID_SHORTCUT,                     /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_CANVAS                       /* selected text color            */
};
GX_PROMPT_PROPERTIES system_diagnostics_ground_shortcut_properties =
{
    GX_STRING_ID_GROUND_SHORTCUT,            /* string id                      */
    GX_FONT_ID_SHORTCUT,                     /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_CANVAS                       /* selected text color            */
};
GX_WINDOW_PROPERTIES system_diagnostics_window_battery_shortcut_properties =
{
    GX_PIXELMAP_ID_BATTERY_SHORTCUT          /* wallpaper pixelmap id          */
};
GX_PROMPT_PROPERTIES system_diagnostics_sys_diagnostics_properties =
{
    GX_STRING_ID_SYS_DIAGNOSTICS,            /* string id                      */
    GX_FONT_ID_SYSTEM_DIAGNOSTICS,           /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_CANVAS                       /* selected text color            */
};
GX_WINDOW_PROPERTIES system_diagnostics_window_ground_shortcut_properties =
{
    GX_PIXELMAP_ID_GROUND_SHORTCUT           /* wallpaper pixelmap id          */
};
GX_WINDOW_PROPERTIES system_diagnostics_aptiv_signature_properties =
{
    GX_PIXELMAP_ID_APTIV_RESIZED             /* wallpaper pixelmap id          */
};

GX_CONST GX_STUDIO_WIDGET system_diagnostics_aptiv_signature_define =
{
    "aptiv_signature",
    GX_TYPE_WINDOW,                          /* widget type                    */
    ID_APTIV_SIGNATURE,                      /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE,                    /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_WINDOW),                       /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {133, 299, 235, 316},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SYSTEM_DIAGNOSTICS_CONTROL_BLOCK, system_diagnostics_aptiv_signature), /* control block */
    (void *) &system_diagnostics_aptiv_signature_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET system_diagnostics_window_ground_shortcut_define =
{
    "window_ground_shortcut",
    GX_TYPE_WINDOW,                          /* widget type                    */
    ID_WINDOW_GROUND_SHORTCUT,               /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_WINDOW),                       /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {61, 62, 206, 125},                      /* widget size                    */
    &system_diagnostics_aptiv_signature_define, /* next widget definition      */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SYSTEM_DIAGNOSTICS_CONTROL_BLOCK, system_diagnostics_window_ground_shortcut), /* control block */
    (void *) &system_diagnostics_window_ground_shortcut_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET system_diagnostics_sys_diagnostics_define =
{
    "sys_diagnostics",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_SYS_DIAGNOSTICS,                      /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_CANVAS,                      /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {14, 6, 233, 29},                        /* widget size                    */
    &system_diagnostics_window_ground_shortcut_define, /* next widget definition */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SYSTEM_DIAGNOSTICS_CONTROL_BLOCK, system_diagnostics_sys_diagnostics), /* control block */
    (void *) &system_diagnostics_sys_diagnostics_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET system_diagnostics_window_battery_shortcut_define =
{
    "window_battery_shortcut",
    GX_TYPE_WINDOW,                          /* widget type                    */
    ID_BATTERY_SHORTCUT,                     /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_WINDOW),                       /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {48, 158, 193, 211},                     /* widget size                    */
    &system_diagnostics_sys_diagnostics_define, /* next widget definition      */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SYSTEM_DIAGNOSTICS_CONTROL_BLOCK, system_diagnostics_window_battery_shortcut), /* control block */
    (void *) &system_diagnostics_window_battery_shortcut_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET system_diagnostics_ground_shortcut_define =
{
    "ground_shortcut",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_GROUND_SHORTCUT,                      /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_CANVAS,                      /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {48, 38, 193, 61},                       /* widget size                    */
    &system_diagnostics_window_battery_shortcut_define, /* next widget definition */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SYSTEM_DIAGNOSTICS_CONTROL_BLOCK, system_diagnostics_ground_shortcut), /* control block */
    (void *) &system_diagnostics_ground_shortcut_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET system_diagnostics_battery_shortcut_define =
{
    "battery_shortcut",
    GX_TYPE_PROMPT,                          /* widget type                    */
    ID_BATTERY_SHORTCUT,                     /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_CANVAS,                      /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {48, 128, 193, 151},                     /* widget size                    */
    &system_diagnostics_ground_shortcut_define, /* next widget definition      */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SYSTEM_DIAGNOSTICS_CONTROL_BLOCK, system_diagnostics_battery_shortcut), /* control block */
    (void *) &system_diagnostics_battery_shortcut_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET system_diagnostics_windowchanger_main_define =
{
    "windowchanger_main",
    GX_TYPE_TEXT_BUTTON,                     /* widget type                    */
    ID_WINDOWCHANGER_MAIN,                   /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_TEXT_BUTTON),                  /* control block size             */
    GX_COLOR_ID_WINDOW_CHANGER,              /* normal color id                */
    GX_COLOR_ID_SHINE,                       /* selected color id              */
    gx_studio_text_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {3, 292, 82, 316},                       /* widget size                    */
    &system_diagnostics_battery_shortcut_define, /* next widget definition     */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SYSTEM_DIAGNOSTICS_CONTROL_BLOCK, system_diagnostics_windowchanger_main), /* control block */
    (void *) &system_diagnostics_windowchanger_main_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET system_diagnostics_define =
{
    "system_diagnostics",
    GX_TYPE_WINDOW,                          /* widget type                    */
    ID_SYS_DIAGNOSTICS,                      /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_DRAW_SELECTED|GX_STYLE_ENABLED,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(SYSTEM_DIAGNOSTICS_CONTROL_BLOCK), /* control block size            */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) gx_studio_system_diagnostics_event_process, /* event function override */
    {0, 0, 239, 319},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &system_diagnostics_windowchanger_main_define, /* child widget             */
    0,                                       /* control block                  */
    (void *) &system_diagnostics_properties  /* extended properties            */
};
GX_CONST GX_STUDIO_WIDGET_ENTRY guiapp_widget_table[] =
{
    { &main_screen_define, (GX_WIDGET *) &main_screen },
    { &system_diagnostics_define, (GX_WIDGET *) &system_diagnostics },
    {GX_NULL, GX_NULL}
};

static GX_WIDGET *gx_studio_nested_widget_create(GX_BYTE *control, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent)
{
    UINT status = GX_SUCCESS;
    GX_WIDGET *widget = GX_NULL;
    GX_VALUE   list_count = 0;
    GX_VALUE   list_total_count = 0;

    if(parent && (parent->gx_widget_type == GX_TYPE_MENU))
    {
        list_total_count = ((GX_MENU *)parent)->gx_menu_list_total_count;
    }

    while(definition && status == GX_SUCCESS)
    {
        if (definition->create_function)
        {
            if (definition->style & GX_STYLE_DYNAMICALLY_ALLOCATED)
            {
                status = gx_widget_allocate(&widget, definition->control_block_size);
                if (status != GX_SUCCESS)
                {
                    return GX_NULL;
                }
            }
            else
            {
                if (control == GX_NULL)
                {
                    return GX_NULL;
                }
                widget = (GX_WIDGET *) (control + definition->control_block_offset);
            }

            status = definition->create_function(definition, widget, parent);

            if(list_count < list_total_count)
            {
                gx_menu_insert((GX_MENU *)parent, widget);
                list_count++;
            }

            if (status == GX_SUCCESS)
            {
                if (definition->widget_type != GX_TYPE_TEMPLATE)
                {
                    gx_widget_fill_color_set(widget, definition->normal_fill_color_id, definition->selected_fill_color_id);
                }

                if (!(definition->status & GX_STATUS_ACCEPTS_FOCUS))
                {
                    gx_widget_status_remove(widget, GX_STATUS_ACCEPTS_FOCUS);
                }

                if (definition->draw_function)
                {
                    gx_widget_draw_set(widget, definition->draw_function);
                }
                if (definition->event_function)
                {
                    gx_widget_event_process_set(widget, definition->event_function);
                }

                #if defined(GX_WIDGET_USER_DATA)
                widget->gx_widget_user_data = definition->user_data;
                #endif

                if (definition->child_widget)
                {
                    gx_studio_nested_widget_create(control, definition->child_widget, widget);
                }
            }
            definition = definition->next_widget;
        }
    }
    return widget;
}

GX_WIDGET *gx_studio_widget_create(GX_BYTE *control, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent)
{
    GX_WIDGET *widget;
    widget = gx_studio_nested_widget_create(control, definition, GX_NULL);

    if (parent && widget)
    {
        gx_widget_attach(parent, widget);
    }
    return widget;
}

UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget)
{
    UINT status = GX_FAILURE;
    GX_CONST GX_STUDIO_WIDGET_ENTRY *entry = guiapp_widget_table;
    GX_WIDGET *widget = GX_NULL;

    while(entry->widget_information)
    {
        if (!strcmp(name, entry->widget_information->widget_name))
        {
            widget = gx_studio_widget_create((GX_BYTE *) entry->widget, entry->widget_information, parent);
            if (widget)
            {
                status = GX_SUCCESS;
            }
            break;
        }
        entry++;
    }

    if (new_widget)
    {
        *new_widget = widget;
    }
    return status;
}

extern GX_CONST GX_THEME *display_1_theme_table[];
extern GX_CONST GX_CHAR **display_1_language_table[];

GX_STUDIO_DISPLAY_INFO guiapp_display_table[1] =
{
    {
    "display_1",
    "display_1_canvas",
    display_1_theme_table,
    display_1_language_table,
    DISPLAY_1_THEME_TABLE_SIZE,
    DISPLAY_1_LANGUAGE_TABLE_SIZE,
    DISPLAY_1_STRING_TABLE_SIZE,
    256,                                     /* x resolution                   */
    320,                                     /* y resolution                   */
    &display_1_control_block,
    &display_1_canvas_control_block,
    &display_1_root_window,
    GX_NULL,                                 /* canvas memory area             */
    163840                                   /* canvas memory size in bytes    */
    }
};

UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *),
    USHORT language, USHORT theme, GX_WINDOW_ROOT **return_root)
{
    GX_CONST GX_THEME *theme_ptr;
    GX_RECTANGLE size;

    GX_STUDIO_DISPLAY_INFO *display_info = &guiapp_display_table[display];


/* create the requested display                                                */

    gx_display_create(display_info->display,
                      display_info->name,
                      driver,
                      (GX_VALUE) display_info->x_resolution,
                      (GX_VALUE) display_info->y_resolution);


/* install the request theme                                                   */

    if(display_info->theme_table)
    {
        theme_ptr = display_info->theme_table[theme];
        if(theme_ptr)
        {
            gx_display_color_table_set(display_info->display, theme_ptr->theme_color_table, theme_ptr->theme_color_table_size);
            
/* install the color palette if required                                       */
            if (display_info->display->gx_display_driver_palette_set &&
                theme_ptr->theme_palette != NULL)
            {
                display_info->display->gx_display_driver_palette_set(display_info->display, theme_ptr->theme_palette, theme_ptr->theme_palette_size);
            }

            gx_display_font_table_set(display_info->display, theme_ptr->theme_font_table, theme_ptr->theme_font_table_size);
            gx_display_pixelmap_table_set(display_info->display, theme_ptr->theme_pixelmap_table, theme_ptr->theme_pixelmap_table_size);
            gx_system_scroll_appearance_set(theme_ptr->theme_vertical_scroll_style, (GX_SCROLLBAR_APPEARANCE *) &theme_ptr->theme_vertical_scrollbar_appearance);
            gx_system_scroll_appearance_set(theme_ptr->theme_horizontal_scroll_style, (GX_SCROLLBAR_APPEARANCE *) &theme_ptr->theme_horizontal_scrollbar_appearance);
            gx_system_language_table_set((GX_CHAR ***) display_info->language_table, display_info->language_table_size, display_info->string_table_size);
            gx_system_active_language_set(language);
        }
    }


/* create the canvas for this display                                          */

    gx_canvas_create(display_info->canvas,
                     display_info->canvas_name,
                     display_info->display,
                     GX_CANVAS_MANAGED | GX_CANVAS_VISIBLE,
                     display_info->x_resolution,
                     display_info->y_resolution,
                     display_info->canvas_memory,
                     display_info->canvas_memory_size);

/* Create the root window for this canvas                                      */

    gx_utility_rectangle_define(&size,
                                0, 0,
                                (GX_VALUE) (display_info->x_resolution - 1),
                                (GX_VALUE) (display_info->y_resolution - 1));

    gx_window_root_create(display_info->root_window,
                          display_info->name,
                          display_info->canvas, GX_STYLE_NONE, 0, &size);
    if (return_root)
    {
        *return_root = display_info->root_window;
    }
    return GX_SUCCESS;
}

/* Provide display driver setup function                                       */

#if defined(GX_TARGET_WIN32) || defined(GX_TARGET_LINUX)

UINT _gx_synergy_display_driver_setup(GX_DISPLAY *display)
{
    win32_synergy_graphics_driver_setup_565rgb(display);
    return GX_SUCCESS;
}
#else
UINT _gx_synergy_display_driver_setup(GX_DISPLAY *display)
{
    _gx_display_driver_565rgb_setup(display, GX_NULL, _gx_dave2d_buffer_toggle);
    display->gx_display_handle =    0;
    display -> gx_display_driver_horizontal_pattern_line_draw  = _gx_dave2d_horizontal_pattern_line_draw_565;
    display -> gx_display_driver_vertical_pattern_line_draw    = _gx_dave2d_vertical_pattern_line_draw_565;
    display -> gx_display_driver_pixel_write                   = _gx_dave2d_pixel_write_565;
    display -> gx_display_driver_pixel_blend                   = _gx_dave2d_pixel_blend_565;
    display -> gx_display_driver_pixelmap_rotate               = _gx_dave2d_pixelmap_rotate_16bpp;
    display -> gx_display_driver_drawing_initiate              = _gx_dave2d_drawing_initiate;
    display -> gx_display_driver_drawing_complete              = _gx_dave2d_drawing_complete;
    display -> gx_display_driver_canvas_copy                   = _gx_dave2d_canvas_copy;
    display -> gx_display_driver_canvas_blend                  = _gx_dave2d_canvas_blend;
    display -> gx_display_driver_simple_line_draw              = _gx_dave2d_simple_line_draw;
    display -> gx_display_driver_horizontal_line_draw          = _gx_dave2d_horizontal_line;
    display -> gx_display_driver_vertical_line_draw            = _gx_dave2d_vertical_line;
    display -> gx_display_driver_polygon_draw                  = _gx_dave2d_polygon_draw;
    display -> gx_display_driver_polygon_fill                  = _gx_dave2d_polygon_fill;
    display -> gx_display_driver_block_move                    = _gx_dave2d_block_move;
    display -> gx_display_driver_pixelmap_draw                 = _gx_dave2d_pixelmap_draw;
    display -> gx_display_driver_horizontal_pixelmap_line_draw = _gx_dave2d_horizontal_pixelmap_line_draw;
    display -> gx_display_driver_alphamap_draw                 = _gx_dave2d_alphamap_draw;
    display -> gx_display_driver_simple_wide_line_draw         = _gx_dave2d_simple_wide_line;
    display -> gx_display_driver_anti_aliased_line_draw        = _gx_dave2d_aliased_line;
    display -> gx_display_driver_anti_aliased_wide_line_draw   = _gx_dave2d_aliased_wide_line;
    display -> gx_display_driver_pixelmap_blend                = _gx_dave2d_pixelmap_blend;
    display -> gx_display_driver_8bit_glyph_draw               = _gx_dave2d_raw_glyph_8bit_draw;
    display -> gx_display_driver_4bit_glyph_draw               = _gx_dave2d_raw_glyph_4bit_draw;
    display -> gx_display_driver_1bit_glyph_draw               = _gx_dave2d_raw_glyph_1bit_draw;
    display -> gx_display_driver_8bit_compressed_glyph_draw    = _gx_dave2d_compressed_glyph_8bit_draw;
    display -> gx_display_driver_4bit_compressed_glyph_draw    = _gx_dave2d_compressed_glyph_4bit_draw;
    display -> gx_display_driver_1bit_compressed_glyph_draw    = _gx_dave2d_compressed_glyph_1bit_draw;
    #if defined(GX_ARC_DRAWING_SUPPORT)
    display -> gx_display_driver_anti_aliased_circle_draw      = _gx_dave2d_aliased_circle_draw;
    display -> gx_display_driver_anti_aliased_wide_circle_draw = _gx_dave2d_aliased_circle_draw;
    display -> gx_display_driver_circle_draw                   = _gx_dave2d_circle_draw;
    display -> gx_display_driver_circle_fill                   = _gx_dave2d_circle_fill;
    display -> gx_display_driver_pie_fill                      = _gx_dave2d_pie_fill;
    display -> gx_display_driver_anti_aliased_arc_draw         = _gx_dave2d_aliased_arc_draw;
    display -> gx_display_driver_arc_draw                      = _gx_dave2d_arc_draw;
    display -> gx_display_driver_arc_fill                      = _gx_dave2d_arc_fill;
    display -> gx_display_driver_anti_aliased_ellipse_draw     = _gx_dave2d_aliased_ellipse_draw;
    display -> gx_display_driver_ellipse_draw                  = _gx_dave2d_ellipse_draw;
    display -> gx_display_driver_ellipse_fill                  = _gx_dave2d_ellipse_fill;
    display -> gx_display_driver_wide_circle_draw              = _gx_dave2d_circle_draw;
    display -> gx_display_driver_anti_aliased_wide_arc_draw    = _gx_dave2d_aliased_arc_draw;
    display -> gx_display_driver_wide_arc_draw                 = _gx_dave2d_arc_draw;
    #endif
    display -> gx_display_driver_jpeg_draw                     = _gx_synergy_jpeg_draw;
    return GX_SUCCESS;
}
#endif
#undef GUIX_STUDIO_GENERATED_FILE
