/*******************************************************************************/
/*  This file is auto-generated by GUIX Studio. Do not edit this file by hand. */
/*  Modifications to this file should only be made by running the GUIX Studio  */
/*  application and re-generating the application resource file(s). For more   */
/*  information please refer to the GUIX Studio user's guide, or visit our web */
/*  site at www.expresslogic.com.                                              */
/*                                                                             */
/*  GUIX Studio Revision 5.4.1.1                                               */
/*  Date (dd.mm.yyyy): 13. 3.2019   Time (hh:mm): 01:21                        */
/*******************************************************************************/


#ifndef _GUIAPP_DISPLAY_1_RESOURCES_H_
#define _GUIAPP_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 256
#define DISPLAY_1_Y_RESOLUTION 320
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_CANVAS 0
#define GX_COLOR_ID_WIDGET_FILL 1
#define GX_COLOR_ID_WINDOW_FILL 2
#define GX_COLOR_ID_DEFAULT_BORDER 3
#define GX_COLOR_ID_WINDOW_BORDER 4
#define GX_COLOR_ID_TEXT 5
#define GX_COLOR_ID_SELECTED_TEXT 6
#define GX_COLOR_ID_SELECTED_FILL 7
#define GX_COLOR_ID_SHADOW 8
#define GX_COLOR_ID_SHINE 9
#define GX_COLOR_ID_BTN_BORDER 10
#define GX_COLOR_ID_BTN_UPPER 11
#define GX_COLOR_ID_BTN_LOWER 12
#define GX_COLOR_ID_BTN_TEXT 13
#define GX_COLOR_ID_SCROLL_FILL 14
#define GX_COLOR_ID_SCROLL_BUTTON 15
#define GX_COLOR_ID_TEXT_INPUT_TEXT 16
#define GX_COLOR_ID_TEXT_INPUT_FILL 17
#define GX_COLOR_ID_SLIDER_TICK 18
#define GX_COLOR_ID_SLIDER_GROOVE_TOP 19
#define GX_COLOR_ID_SLIDER_GROOVE_BOTTOM 20
#define GX_COLOR_ID_SLIDER_NEEDLE_OUTLINE 21
#define GX_COLOR_ID_SLIDER_NEEDLE_FILL 22
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE1 23
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE2 24
#define GX_COLOR_ID_WINDOW_CHANGER 25
#define DISPLAY_1_COLOR_TABLE_SIZE 26

/* Font ID definitions                                                         */

#define GX_FONT_ID_SYSTEM 0
#define GX_FONT_ID_BUTTON 1
#define GX_FONT_ID_PROMPT 2
#define GX_FONT_ID_TEXT_INPUT 3
#define GX_FONT_ID_SPEED_TEXT 4
#define GX_FONT_ID_SW_AND_HW_VERSIONS 5
#define GX_FONT_ID_SW_AND_HW 6
#define GX_FONT_ID_EMBEDDED_SW 7
#define GX_FONT_ID_SW_ENGINEERS 8
#define GX_FONT_ID_ENGINEERS 9
#define GX_FONT_ID_DUTY_CYCLE 10
#define GX_FONT_ID_SHORTCUT 11
#define GX_FONT_ID_SYSTEM_DIAGNOSTICS 12
#define GX_FONT_ID_WINDOW_CHANGER 13
#define GX_FONT_ID_ENABLE_SYS_DIAGNOSTICS 14
#define DISPLAY_1_FONT_TABLE_SIZE 15

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_RADIO_ON 1
#define GX_PIXELMAP_ID_RADIO_OFF 2
#define GX_PIXELMAP_ID_CHECKBOX_ON 3
#define GX_PIXELMAP_ID_CHECKBOX_OFF 4
#define GX_PIXELMAP_ID_APTIV_COMPRESSED 5
#define GX_PIXELMAP_ID_APTIV_RESIZED 6
#define GX_PIXELMAP_ID_BATTERY_SHORTCUT 7
#define GX_PIXELMAP_ID_GROUND_SHORTCUT 8
#define GX_PIXELMAP_ID_MAIN_SCREEN_1 9
#define GX_PIXELMAP_ID_SPEED_CYCLE 10
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 11

/* String Ids                                                                  */

#define GX_STRING_ID_EMBEDDED_SW 1
#define GX_STRING_ID_PERCENTAGE 2
#define GX_STRING_ID_SPEED_PLACEHOLDER 3
#define GX_STRING_ID_RPM 4
#define GX_STRING_ID_HW_VERSION 5
#define GX_STRING_ID_SW_VERSION 6
#define GX_STRING_ID_CESEQ_C001_CESEQ_P001 7
#define GX_STRING_ID_M4_DC_MVC 8
#define GX_STRING_ID_SOFTWARE_ENGINEERS 9
#define GX_STRING_ID_JOSUE_URIBE 10
#define GX_STRING_ID_GEMMA_CORONA 11
#define GX_STRING_ID_VICTOR_ALVARADO 12
#define GX_STRING_ID_DUTY_CYCLE 13
#define GX_STRING_ID_SPEED_CMD_PLACEHOLDER 14
#define GX_STRING_ID_BATTERY_SHORTCUT 15
#define GX_STRING_ID_GROUND_SHORTCUT 16
#define GX_STRING_ID_SYS_DIAGNOSTICS 17
#define GX_STRING_ID_GO_TO_MAIN_SCREEN 18
#define GX_STRING_ID_WINDOW_CHANGER_MAIN 19
#define GX_STRING_ID_ENABLE_SYS_DIAGNOSTICS 20
#define GX_STRING_ID_WINDOW_CHANGER_SYS 21
#define DISPLAY_1_STRING_TABLE_SIZE 22

#endif                                       /* sentry                         */
